input {
    kb_layout = us
    kb_options = ctrl:nocaps
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        clickfinger_behavior = true
        scroll_factor = 1.2
    }
    numlock_by_default = true
}
