#!/bin/bash
# Keybind cheat sheet for Hyprland

echo "VOID Keybinds"
echo "============="
echo ""
echo "Core"
echo "  Super+Return     Terminal (Ghostty)"
echo "  Super+Q          Close window"
echo "  Super+Shift+E    Exit Hyprland"
echo "  Super+V          Toggle floating"
echo "  Super+F          Fullscreen"
echo "  Super+Space      Fullscreen (no bar)"
echo "  Super+L          Lock screen"
echo ""
echo "Apps"
echo "  Super+D          App launcher (Fuzzel)"
echo "  Super+E          File manager (Yazi)"
echo "  Super+X          Power menu"
echo "  Super+W          Wallpaper picker"
echo "  Super+Shift+W    Next wallpaper"
echo "  Super+grave      App launcher (alt)"
echo ""
echo "Focus (vim keys)"
echo "  Super+H/J/K/L    Move focus left/down/up/right"
echo "  Super+arrows     Move focus"
echo ""
echo "Move windows"
echo "  Super+Shift+H/J/K/L  Move window"
echo "  Super+Shift+arrows   Move window"
echo ""
echo "Resize"
echo "  Super+Ctrl+arrows    Resize window"
echo ""
echo "Workspaces"
echo "  Super+1-9       Switch workspace"
echo "  Super+Shift+1-9 Move to workspace"
echo "  Super+scroll    Scroll workspaces"
echo ""
echo "Special"
echo "  Super+S          Toggle special workspace"
echo "  Super+Shift+S    Move to special"
echo ""
echo "Screenshots"
echo "  Print            Area select"
echo "  Shift+Print      Full screen"
echo "  Super+Print      Save to ~/Pictures"
echo ""
echo "Media"
echo "  Volume keys      Volume"
echo "  Brightness keys  Brightness"
echo "  Media keys       Play/Pause/Next/Prev"
